import { DESIGN_PREVIEW, fxPlaybooks } from '@/lib/designFixtures';
import { supabase } from '@/lib/supabase';
import { colors } from '@/theme/colors';

/**
 * Coach-facing data access, backed by real Supabase tables (no mock data).
 *
 * Access chain (verified against live RLS policies):
 *  - team_coaches.user_id = me, is_active  -> which teams I coach
 *  - events.team_id in (my teams)          -> my teams' schedule
 *  - event_responses / team_members        -> RSVP roll-up per event
 *  - player_feedback (coach_id = me)       -> my notes on a player for an event
 *  - player_measurements (is_current)      -> latest height/weight/wingspan
 *  - games_live_session / game_events_log  -> box-score source (no in-app
 *    recorder exists yet anywhere in this app, mockup included, so these
 *    almost always resolve to empty results today — the queries are real,
 *    the data just hasn't been generated by anything yet)
 *  - playbooks / plays (canvas_data jsonb) -> saved drill diagrams
 *
 * There is no "events DELETE" RLS policy (by design — nothing may hard
 * delete a scheduled event), so "delete" here means `is_active = false`,
 * and every read filters `is_active = true` explicitly.
 */

const TEAM_COLORS = [colors.navy, colors.buzzer, colors.purple, colors.blue, colors.green, colors.gold];

// ---------------------------------------------------------------------------
// Teams
// ---------------------------------------------------------------------------

export type CoachTeam = {
  id: string; // teams.id
  clubId: string;
  name: string;
  clubName: string;
  label: string; // "{club} · {team}"
  color: string;
};

export async function getMyTeams(personId: string): Promise<CoachTeam[]> {
  const { data, error } = await supabase
    .from('team_coaches')
    .select('team_id, teams ( id, name, club_id, clubs ( name ) )')
    .eq('user_id', personId)
    .eq('is_active', true);
  if (error) throw error;

  const rows = data ?? [];
  const seen = new Set<string>();
  const teams: CoachTeam[] = [];
  let i = 0;
  for (const r of rows) {
    const t = (r as any).teams as { id: string; name: string; club_id: string; clubs?: { name: string } } | null;
    if (!t || seen.has(t.id)) continue;
    seen.add(t.id);
    teams.push({
      id: t.id,
      clubId: t.club_id,
      name: t.name,
      clubName: t.clubs?.name ?? '',
      label: t.clubs?.name ? `${t.clubs.name} · ${t.name}` : t.name,
      color: TEAM_COLORS[i % TEAM_COLORS.length],
    });
    i += 1;
  }
  return teams;
}

export async function getMyProfile(personId: string): Promise<{ name: string; initials: string }> {
  const { data, error } = await supabase.from('users').select('first_name, last_name').eq('id', personId).single();
  if (error) throw error;
  const first = data?.first_name ?? '';
  const last = data?.last_name ?? '';
  const name = [first, last].filter(Boolean).join(' ') || 'Coach';
  const initials = `${first[0] ?? ''}${last[0] ?? ''}`.toUpperCase() || '?';
  return { name, initials };
}

// ---------------------------------------------------------------------------
// Roster
// ---------------------------------------------------------------------------

export type RosterPlayer = {
  id: string; // players.id
  teamId: string;
  jersey: number | null;
  name: string;
  firstName: string;
  initials: string;
  position: string | null;
};

/** Every active roster row for `teamIds`, one entry per player per team. */
export async function getRosters(teamIds: string[]): Promise<RosterPlayer[]> {
  if (!teamIds.length) return [];
  const { data, error } = await supabase
    .from('team_members')
    .select('team_id, jersey_number, court_position, players ( id, first_name, last_name )')
    .in('team_id', teamIds)
    .eq('is_active', true);
  if (error) throw error;

  return (data ?? []).map((r) => {
    const p = (r as any).players as { id: string; first_name: string | null; last_name: string | null } | null;
    const first = p?.first_name ?? '';
    const last = p?.last_name ?? '';
    const name = [first, last].filter(Boolean).join(' ') || 'Player';
    return {
      id: p?.id as string,
      teamId: r.team_id as string,
      jersey: (r.jersey_number as number | null) ?? null,
      name,
      firstName: first || name,
      initials: `${first[0] ?? ''}${last[0] ?? ''}`.toUpperCase() || '?',
      position: (r.court_position as string | null) ?? null,
    };
  });
}

// ---------------------------------------------------------------------------
// Events (schedule)
// ---------------------------------------------------------------------------

export type CoachEvent = {
  id: string;
  teamId: string;
  type: string; // 'practice' | 'game'
  title: string;
  eventStatus: string; // 'scheduled' | 'completed' | 'cancelled'
  startsAt: string;
  endsAt: string;
  facilityId: string | null;
  facilityName: string | null;
  opponentName: string | null;
  isHomeGame: boolean | null;
  confirmed: number;
  declined: number;
  pending: number;
  roster: number;
};

async function withRsvpCounts(events: any[], rosterByTeam: Map<string, RosterPlayer[]>): Promise<CoachEvent[]> {
  const eventIds = events.map((e) => e.id as string);
  const { data: responseRows } = eventIds.length
    ? await supabase.from('event_responses').select('event_id, player_id, status').in('event_id', eventIds)
    : { data: [] as any[] };

  const byEvent = new Map<string, { attending: number; declined: number; responded: Set<string> }>();
  for (const r of responseRows ?? []) {
    const key = r.event_id as string;
    const bucket = byEvent.get(key) ?? { attending: 0, declined: 0, responded: new Set<string>() };
    bucket.responded.add(r.player_id as string);
    if (r.status === 'attending') bucket.attending += 1;
    if (r.status === 'not_attending') bucket.declined += 1;
    byEvent.set(key, bucket);
  }

  return events.map((e) => {
    const roster = rosterByTeam.get(e.team_id as string) ?? [];
    const bucket = byEvent.get(e.id as string);
    const confirmed = bucket?.attending ?? 0;
    const declined = bucket?.declined ?? 0;
    return {
      id: e.id as string,
      teamId: e.team_id as string,
      type: e.type as string,
      title: e.title as string,
      eventStatus: e.status as string,
      startsAt: e.starts_at as string,
      endsAt: e.ends_at as string,
      facilityId: (e.facility_id as string | null) ?? null,
      facilityName: (e as any).facilities?.name ?? null,
      opponentName: (e.opponent_name as string | null) ?? null,
      isHomeGame: (e.is_home_game as boolean | null) ?? null,
      confirmed,
      declined,
      pending: Math.max(roster.length - confirmed - declined, 0),
      roster: roster.length,
    };
  });
}

export async function getTeamsEvents(
  teams: CoachTeam[],
  range: { from: Date; to: Date },
  roster?: RosterPlayer[]
): Promise<CoachEvent[]> {
  const teamIds = teams.map((t) => t.id);
  if (!teamIds.length) return [];

  const { data: eventRows, error } = await supabase
    .from('events')
    .select('id, team_id, type, title, starts_at, ends_at, status, opponent_name, is_home_game, facility_id, facilities ( name )')
    .in('team_id', teamIds)
    .eq('is_active', true)
    .gte('starts_at', range.from.toISOString())
    .lte('starts_at', range.to.toISOString())
    .order('starts_at', { ascending: true });
  if (error) throw error;

  const rosterList = roster ?? (await getRosters(teamIds));
  const rosterByTeam = new Map<string, RosterPlayer[]>();
  for (const p of rosterList) {
    const list = rosterByTeam.get(p.teamId) ?? [];
    list.push(p);
    rosterByTeam.set(p.teamId, list);
  }

  return withRsvpCounts(eventRows ?? [], rosterByTeam);
}

/** The next scheduled (future, not cancelled) event for one team, or null. */
export async function getNextEventForTeam(teamId: string, roster: RosterPlayer[]): Promise<CoachEvent | null> {
  const { data, error } = await supabase
    .from('events')
    .select('id, team_id, type, title, starts_at, ends_at, status, opponent_name, is_home_game, facility_id, facilities ( name )')
    .eq('team_id', teamId)
    .eq('is_active', true)
    .eq('status', 'scheduled')
    .gte('starts_at', new Date().toISOString())
    .order('starts_at', { ascending: true })
    .limit(1);
  if (error) throw error;
  if (!data?.length) return null;

  const rosterByTeam = new Map([[teamId, roster.filter((p) => p.teamId === teamId)]]);
  const [event] = await withRsvpCounts(data, rosterByTeam);
  return event;
}

/** Recent practices for one team (most recent first) — used by the Review tab's practice picker. */
export async function getRecentPractices(teamId: string, limit = 10): Promise<CoachEvent[]> {
  const { data, error } = await supabase
    .from('events')
    .select('id, team_id, type, title, starts_at, ends_at, status, opponent_name, is_home_game, facility_id, facilities ( name )')
    .eq('team_id', teamId)
    .eq('is_active', true)
    .eq('type', 'practice')
    .lte('starts_at', new Date().toISOString())
    .order('starts_at', { ascending: false })
    .limit(limit);
  if (error) throw error;
  const rosterByTeam = new Map([[teamId, await getRosters([teamId])]]);
  return withRsvpCounts(data ?? [], rosterByTeam);
}

/** Most recently completed games for one team (most recent first). */
export async function getRecentGames(teamId: string, limit = 5): Promise<CoachEvent[]> {
  const { data, error } = await supabase
    .from('events')
    .select('id, team_id, type, title, starts_at, ends_at, status, opponent_name, is_home_game, facility_id, facilities ( name )')
    .eq('team_id', teamId)
    .eq('is_active', true)
    .eq('type', 'game')
    .eq('status', 'completed')
    .order('starts_at', { ascending: false })
    .limit(limit);
  if (error) throw error;
  const rosterByTeam = new Map([[teamId, await getRosters([teamId])]]);
  return withRsvpCounts(data ?? [], rosterByTeam);
}

export type EventInput = {
  teamId: string;
  type: 'practice' | 'game';
  title: string;
  startsAt: string;
  endsAt: string;
  facilityId?: string | null;
  opponentName?: string | null;
  isHomeGame?: boolean | null;
};

export async function createEvent(input: EventInput, createdBy: string): Promise<void> {
  const { error } = await supabase.from('events').insert({
    team_id: input.teamId,
    type: input.type,
    title: input.title,
    starts_at: input.startsAt,
    ends_at: input.endsAt,
    facility_id: input.facilityId ?? null,
    opponent_name: input.opponentName ?? null,
    is_home_game: input.isHomeGame ?? null,
    status: 'scheduled',
    created_by: createdBy,
  });
  if (error) throw error;
}

export async function updateEvent(eventId: string, patch: Partial<EventInput>): Promise<void> {
  const payload: Record<string, unknown> = {};
  if (patch.title !== undefined) payload.title = patch.title;
  if (patch.startsAt !== undefined) payload.starts_at = patch.startsAt;
  if (patch.endsAt !== undefined) payload.ends_at = patch.endsAt;
  if (patch.facilityId !== undefined) payload.facility_id = patch.facilityId;
  if (patch.opponentName !== undefined) payload.opponent_name = patch.opponentName;
  if (patch.isHomeGame !== undefined) payload.is_home_game = patch.isHomeGame;

  const { error } = await supabase.from('events').update(payload).eq('id', eventId);
  if (error) throw error;
}

/** Soft-delete — there's no DELETE policy on events by design; every read here filters is_active = true. */
export async function deactivateEvent(eventId: string): Promise<void> {
  const { error } = await supabase.from('events').update({ is_active: false }).eq('id', eventId);
  if (error) throw error;
}

export type Facility = { id: string; name: string };

export async function getFacilities(clubId: string): Promise<Facility[]> {
  const { data, error } = await supabase.from('facilities').select('id, name').eq('club_id', clubId).eq('is_active', true);
  if (error) throw error;
  return (data ?? []) as Facility[];
}

// ---------------------------------------------------------------------------
// RSVP status per player, for one event (Players tab + Schedule detail)
// ---------------------------------------------------------------------------

export type EventStatus = 'attending' | 'not_attending' | 'undecided' | 'injured';

export async function getRsvpStatusForEvent(eventId: string): Promise<Map<string, EventStatus>> {
  const { data, error } = await supabase.from('event_responses').select('player_id, status').eq('event_id', eventId);
  if (error) throw error;
  const map = new Map<string, EventStatus>();
  for (const r of data ?? []) map.set(r.player_id as string, r.status as EventStatus);
  return map;
}

// ---------------------------------------------------------------------------
// Player feedback (Review tab)
// ---------------------------------------------------------------------------

export type FeedbackType = { id: number; name: string };

export async function getFeedbackTypes(): Promise<FeedbackType[]> {
  const { data, error } = await supabase.from('feedback_type').select('id, feedback_name').eq('is_active', true);
  if (error) throw error;
  return (data ?? []).map((r) => ({ id: r.id as number, name: r.feedback_name as string }));
}

export type FeedbackEntry = { id: string; note: string | null; feedbackTypeId: number | null };

/** This coach's existing feedback for every player, for one event — keyed by player_id. */
export async function getFeedbackForEvent(eventId: string, coachId: string): Promise<Map<string, FeedbackEntry>> {
  const { data, error } = await supabase
    .from('player_feedback')
    .select('id, player_id, note, feedback_type_id')
    .eq('event_id', eventId)
    .eq('coach_id', coachId)
    .eq('is_active', true);
  if (error) throw error;
  const map = new Map<string, FeedbackEntry>();
  for (const r of data ?? []) {
    map.set(r.player_id as string, { id: r.id as string, note: r.note as string | null, feedbackTypeId: (r.feedback_type_id as number | null) ?? null });
  }
  return map;
}

/** No unique constraint backs this table, so this looks up any existing row for
 * (coach, player, event) first and updates it — otherwise inserts a new one. */
export async function saveFeedback(
  existingId: string | null,
  input: { coachId: string; playerId: string; teamId: string; eventId: string; note: string; feedbackTypeId: number | null }
): Promise<string> {
  if (existingId) {
    const { error } = await supabase
      .from('player_feedback')
      .update({ note: input.note, feedback_type_id: input.feedbackTypeId })
      .eq('id', existingId);
    if (error) throw error;
    return existingId;
  }

  const { data, error } = await supabase
    .from('player_feedback')
    .insert({
      coach_id: input.coachId,
      player_id: input.playerId,
      team_id: input.teamId,
      event_id: input.eventId,
      note: input.note,
      feedback_type_id: input.feedbackTypeId,
    })
    .select('id')
    .single();
  if (error) throw error;
  return data.id as string;
}

// ---------------------------------------------------------------------------
// Stats: physical measurements, last-game box score, shooting trend
// ---------------------------------------------------------------------------

export type Measurement = {
  playerId: string;
  heightCm: number | null;
  weightKg: number | null;
  wingspanCm: number | null;
  verticalJumpCm: number | null;
  measuredOn: string | null;
};

export async function getCurrentMeasurements(playerIds: string[]): Promise<Map<string, Measurement>> {
  if (!playerIds.length) return new Map();
  const { data, error } = await supabase
    .from('player_measurements')
    .select('player_id, height_cm, weight_kg, wingspan_cm, vertical_jump_cm, measured_on')
    .in('player_id', playerIds)
    .eq('is_current', true);
  if (error) throw error;
  const map = new Map<string, Measurement>();
  for (const r of data ?? []) {
    map.set(r.player_id as string, {
      playerId: r.player_id as string,
      heightCm: (r.height_cm as number | null) ?? null,
      weightKg: (r.weight_kg as number | null) ?? null,
      wingspanCm: (r.wingspan_cm as number | null) ?? null,
      verticalJumpCm: (r.vertical_jump_cm as number | null) ?? null,
      measuredOn: (r.measured_on as string | null) ?? null,
    });
  }
  return map;
}

export type BoxScoreRow = {
  playerId: string;
  pts: number;
  reb: number;
  ast: number;
  stl: number;
  blk: number;
  fgMade: number;
  fgAttempted: number;
  fgPct: number | null;
};

/**
 * Aggregates `game_events_log` into a per-player box score for one game
 * session. event_type is free-text; this recognizes the shot/stat vocabulary
 * a live-game recorder would use ('fg2'/'fg3'/'ft' + is_success for makes,
 * 'reb'/'ast'/'stl'/'blk' as counting events). No screen in this app writes
 * that log yet, so today this will almost always resolve to an empty list —
 * that's a real "no data recorded" result, not a bug.
 */
export async function getLastGameBoxScore(teamId: string): Promise<{ event: CoachEvent | null; rows: BoxScoreRow[]; score: { home: number; away: number } | null }> {
  const [lastGame] = await getRecentGames(teamId, 1);
  if (!lastGame) return { event: null, rows: [], score: null };

  const { data: sessionRows } = await supabase
    .from('games_live_session')
    .select('id, home_score, away_score')
    .eq('event_id', lastGame.id)
    .limit(1);
  const session = sessionRows?.[0];
  if (!session) return { event: lastGame, rows: [], score: null };

  const { data: logRows } = await supabase
    .from('game_events_log')
    .select('player_id, event_type, is_success')
    .eq('game_session_id', session.id);

  const byPlayer = new Map<string, BoxScoreRow>();
  const get = (playerId: string) => {
    let row = byPlayer.get(playerId);
    if (!row) {
      row = { playerId, pts: 0, reb: 0, ast: 0, stl: 0, blk: 0, fgMade: 0, fgAttempted: 0, fgPct: null };
      byPlayer.set(playerId, row);
    }
    return row;
  };

  for (const log of logRows ?? []) {
    const row = get(log.player_id as string);
    const type = log.event_type as string;
    const success = Boolean(log.is_success);
    if (type === 'fg2' || type === 'fg3') {
      row.fgAttempted += 1;
      if (success) {
        row.fgMade += 1;
        row.pts += type === 'fg3' ? 3 : 2;
      }
    } else if (type === 'ft' && success) {
      row.pts += 1;
    } else if (type === 'reb') row.reb += 1;
    else if (type === 'ast') row.ast += 1;
    else if (type === 'stl') row.stl += 1;
    else if (type === 'blk') row.blk += 1;
  }

  for (const row of byPlayer.values()) {
    row.fgPct = row.fgAttempted > 0 ? Math.round((row.fgMade / row.fgAttempted) * 100) : null;
  }

  return { event: lastGame, rows: [...byPlayer.values()], score: { home: session.home_score as number, away: session.away_score as number } };
}

export type GameLogEntry = { event: CoachEvent; row: BoxScoreRow };

/** One player's box score for each of their last `limit` completed games (most recent first). */
export async function getPlayerGameLog(teamId: string, playerId: string, limit = 5): Promise<GameLogEntry[]> {
  const games = await getRecentGames(teamId, limit);
  if (!games.length) return [];

  const eventIds = games.map((g) => g.id);
  const { data: sessionRows } = await supabase.from('games_live_session').select('id, event_id').in('event_id', eventIds);
  const sessions = sessionRows ?? [];
  if (!sessions.length) return [];

  const sessionByEvent = new Map(sessions.map((s) => [s.event_id as string, s.id as string]));
  const { data: logRows } = await supabase
    .from('game_events_log')
    .select('game_session_id, event_type, is_success')
    .eq('player_id', playerId)
    .in(
      'game_session_id',
      sessions.map((s) => s.id as string)
    );

  const bySession = new Map<string, BoxScoreRow>();
  const get = (sessionId: string) => {
    let row = bySession.get(sessionId);
    if (!row) {
      row = { playerId, pts: 0, reb: 0, ast: 0, stl: 0, blk: 0, fgMade: 0, fgAttempted: 0, fgPct: null };
      bySession.set(sessionId, row);
    }
    return row;
  };
  for (const log of logRows ?? []) {
    const row = get(log.game_session_id as string);
    const type = log.event_type as string;
    const success = Boolean(log.is_success);
    if (type === 'fg2' || type === 'fg3') {
      row.fgAttempted += 1;
      if (success) {
        row.fgMade += 1;
        row.pts += type === 'fg3' ? 3 : 2;
      }
    } else if (type === 'ft' && success) row.pts += 1;
    else if (type === 'reb') row.reb += 1;
    else if (type === 'ast') row.ast += 1;
    else if (type === 'stl') row.stl += 1;
    else if (type === 'blk') row.blk += 1;
  }
  for (const row of bySession.values()) row.fgPct = row.fgAttempted > 0 ? Math.round((row.fgMade / row.fgAttempted) * 100) : null;

  const out: GameLogEntry[] = [];
  for (const g of games) {
    const sessionId = sessionByEvent.get(g.id);
    if (!sessionId) continue;
    const row = bySession.get(sessionId);
    if (row && (row.fgAttempted > 0 || row.pts > 0 || row.reb > 0 || row.ast > 0 || row.stl > 0 || row.blk > 0)) {
      out.push({ event: g, row });
    }
  }
  return out;
}

export type TrendPoint = { eventId: string; label: string; fgPct: number | null };

/** Shooting % per game, most recent N completed games, for one player. */
export async function getShootingTrend(teamId: string, playerId: string, limit = 6): Promise<TrendPoint[]> {
  const games = await getRecentGames(teamId, limit);
  if (!games.length) return [];

  const eventIds = games.map((g) => g.id);
  const { data: sessionRows } = await supabase.from('games_live_session').select('id, event_id').in('event_id', eventIds);
  const sessionByEvent = new Map((sessionRows ?? []).map((s) => [s.event_id as string, s.id as string]));
  const sessionIds = [...sessionByEvent.values()];
  if (!sessionIds.length) return games.map((g) => ({ eventId: g.id, label: formatShortDate(g.startsAt), fgPct: null })).reverse();

  const { data: logRows } = await supabase
    .from('game_events_log')
    .select('game_session_id, player_id, event_type, is_success')
    .eq('player_id', playerId)
    .in('game_session_id', sessionIds)
    .in('event_type', ['fg2', 'fg3']);

  const bySession = new Map<string, { made: number; attempted: number }>();
  for (const log of logRows ?? []) {
    const key = log.game_session_id as string;
    const bucket = bySession.get(key) ?? { made: 0, attempted: 0 };
    bucket.attempted += 1;
    if (log.is_success) bucket.made += 1;
    bySession.set(key, bucket);
  }

  return games
    .map((g) => {
      const sessionId = sessionByEvent.get(g.id);
      const bucket = sessionId ? bySession.get(sessionId) : undefined;
      const fgPct = bucket && bucket.attempted > 0 ? Math.round((bucket.made / bucket.attempted) * 100) : null;
      return { eventId: g.id, label: formatShortDate(g.startsAt), fgPct };
    })
    .reverse();
}

function formatShortDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', { weekday: 'short' });
}

// ---------------------------------------------------------------------------
// Playbook
// ---------------------------------------------------------------------------

export type PlaybookCategory = 'offense' | 'defense' | 'inbound' | 'drill' | 'special';

export type Play = {
  id: string;
  playbookId: string;
  title: string;
  canvasData: CourtDiagram;
  notes: string | null;
  displayOrder: number;
};

export type Playbook = {
  id: string;
  teamId: string | null;
  title: string;
  category: PlaybookCategory | null;
  plays: Play[];
};

export type CourtMarker = {
  id: string; // "O1".."O5" | "X1".."X5"
  side: 'offense' | 'defense';
  num: number;
  x: number; // 0..1 normalized within the court box
  y: number;
  path: { x: number; y: number }[]; // movement trail, normalized, empty if not drawn
};

export type CourtDiagram = { markers: CourtMarker[] };

export async function getPlaybooks(teamId: string): Promise<Playbook[]> {
  if (DESIGN_PREVIEW) return fxPlaybooks;
  const { data, error } = await supabase
    .from('playbooks')
    .select('id, team_id, title, category, plays ( id, playbook_id, title, canvas_data, notes, display_order )')
    .eq('team_id', teamId)
    .eq('is_active', true)
    .order('created_at', { ascending: false });
  if (error) throw error;

  return (data ?? []).map((pb) => ({
    id: pb.id as string,
    teamId: (pb.team_id as string | null) ?? null,
    title: pb.title as string,
    category: (pb.category as PlaybookCategory | null) ?? null,
    plays: ((pb as any).plays ?? [])
      .filter((p: any) => p.is_active !== false)
      .sort((a: any, b: any) => (a.display_order ?? 0) - (b.display_order ?? 0))
      .map((p: any) => ({
        id: p.id as string,
        playbookId: p.playbook_id as string,
        title: p.title as string,
        canvasData: (p.canvas_data as CourtDiagram) ?? { markers: [] },
        notes: (p.notes as string | null) ?? null,
        displayOrder: (p.display_order as number) ?? 0,
      })),
  }));
}

export async function createPlaybook(input: { authorId: string; clubId: string; teamId: string; title: string; category: PlaybookCategory }): Promise<string> {
  const { data, error } = await supabase
    .from('playbooks')
    .insert({ author_id: input.authorId, club_id: input.clubId, team_id: input.teamId, title: input.title, category: input.category })
    .select('id')
    .single();
  if (error) throw error;
  return data.id as string;
}

export async function savePlay(input: { playbookId: string; title: string; canvasData: CourtDiagram; displayOrder: number }): Promise<void> {
  const { error } = await supabase.from('plays').insert({
    playbook_id: input.playbookId,
    title: input.title,
    canvas_data: input.canvasData,
    display_order: input.displayOrder,
  });
  if (error) throw error;
}

export const DEFAULT_DIAGRAM: CourtDiagram = {
  markers: [
    { id: 'O1', side: 'offense', num: 1, x: 0.25, y: 0.78, path: [] },
    { id: 'O2', side: 'offense', num: 2, x: 0.4, y: 0.42, path: [] },
    { id: 'O3', side: 'offense', num: 3, x: 0.6, y: 0.42, path: [] },
    { id: 'O4', side: 'offense', num: 4, x: 0.75, y: 0.78, path: [] },
    { id: 'O5', side: 'offense', num: 5, x: 0.5, y: 0.65, path: [] },
  ],
};
